version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - YasushiKobayashi
  assignees:
    - YasushiKobayashi

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - YasushiKobayashi
  assignees:
    - YasushiKobayashi

- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - YasushiKobayashi
  assignees:
    - YasushiKobayashi
