---
root: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

env:
  browser: true
  node: true
  es6: true

plugins:
  - simple-import-sort
  - import
  - react
  - jsx-a11y
  - prettier
  - "@typescript-eslint"
  - react-hooks
  - import-access

parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"


globals:
  __DEV__: true
  __SERVER__: true

rules:
  valid-jsdoc: 2
  semi: 0
  object-shorthand: 0
  no-shadow: 0
  class-methods-use-this: 0
  no-console: 0
  no-unresolved: 0
  no-else-return: 0
  arrow-body-style: 0
  no-new: 0
  no-param-reassign: 0
  consistent-return: 0
  no-return-assign: 0
  no-nested-ternary: 0
  arrow-parens: 0
  global-require: 1
  object-curly-newline: 0
  function-paren-newline: 0
  no-await-in-loop: 1
  no-undef: 0
  no-unused-vars: 0
  no-redeclare: 1
  operator-linebreak: 1
  lines-between-class-members: 0
  prefer-spread: 2
  no-use-before-define: 0
  camelcase: 1
  no-underscore-dangle: 1

  "@typescript-eslint/no-use-before-define": 1
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/no-var-requires": 1
  "@typescript-eslint/indent": 0
  "@typescript-eslint/no-var-require": 0
  "@typescript-eslint/explicit-function-return-type": 1
  "@typescript-eslint/member-delimiter-style":
  - error
  - multiline:
      delimiter: none
      requireLast: false
    singleline:
      delimiter: comma
      requireLast: false

  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/prefer-default-export: 0
  import/first: 2
  import/newline-after-import: 2
  import/no-duplicates: 2
  simple-import-sort/exports: 2
  simple-import-sort/imports:
    - error
    - groups:
      - ["^react", "^@?\\w"]
      - ["^\\u0000"]
      - ["^(@pocket-sommelier/*)(/.*|$)"]
      - ["^(@/*)(/.*|$)"]
      - ["^\\.\\.(?!/?$)", "^\\.\\./?$"]
      - ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"]
      - ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"]
      - ["^.+\\.s?css$"]

  react/no-danger: 0
  react/no-string-refs: 0
  react/prefer-stateless-function: 0
  react/jsx-wrap-multilines: 0
  react/sort-comp: 0
  react/jsx-closing-bracket-location: 1
  react/jsx-filename-extension: 0
  react/prop-types: 0
  react/button-has-type: 1
  react/jsx-props-no-spreading: 0
  react/function-component-definition: 0
  react/jsx-no-useless-fragment: 1
  react/require-default-props: 0

  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/img-redundant-alt: 1
  jsx-a11y/anchor-is-valid: 1
  jsx-a11y/click-events-have-key-events: 1
  jsx-a11y/no-noninteractive-element-interactions: 1
  jsx-a11y/label-has-for: 0
  jsx-a11y/anchor-has-content: 0
  jsx-filename-extension: 0
  jsx-quotes: 0
