bucketName: ${env.BUCKET_NAME}
bucketRegion: ${env.REGION}
distributionId: ${env.DISTRIBUTION_ID}

serverless-next-isr:
  component: "../../node_modules/@sls-next/serverless-component"
  inputs:
    name:
        defaultLambda: serverless-next-isr
    build:
      cmd: ../../node_modules/.bin/next
      env:
        NODE_ENV: production
    bucketName: ${bucketName}
    bucketRegion: ${bucketRegion}
    cloudfront:
      distributionId: ${distributionId}
    runtime:
      defaultLambda: "nodejs14.x"
      apiLambda: "nodejs14.x"
      imageLambda: "nodejs14.x"

    /:
      minTTL: 1
      maxTTL: 1
      defaultTTL: 1

    /*:
      minTTL: 1
      maxTTL: 1
      defaultTTL: 1
