bucketName: qtecfsl-kcxc4fp
bucketRegion: ap-northeast-1
distributionId: E328WXB08DXVWZ

serverless-next-isr:
  component: "../../node_modules/@sls-next/serverless-component"
  inputs:
    build:
      cmd: ../../node_modules/.bin/next
      env:
        NODE_ENV: production
    name: "serverless-next-isr"
    bucketName: ${bucketName}
    bucketRegion: ${bucketRegion}
    cloudfront:
      distributionId: ${distributionId}
    runtime:
      defaultLambda: "nodejs14.x"
      apiLambda: "nodejs14.x"
      imageLambda: "nodejs14.x"

    /:
      minTTL: 1
      maxTTL: 1
      defaultTTL: 1

    /*:
      minTTL: 1
      maxTTL: 1
      defaultTTL: 1
