name: Test workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12"]
    env:
      NODE_ENV: test
      TEST_ARTIFACTS: /tmp/artifacts

    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p $TEST_ARTIFACTS
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn
      - run: yarn lint:ts
      # - run: yarn lint:sass
      - run: yarn test
      - uses: codecov/codecov-action@v1
      - run: yarn type-check
      - run: yarn build
      - run: yarn cp-artifacts
      - run: yarn cp-artifacts
        if: failure()
      - uses: actions/upload-artifact@master
        with:
          name: test-artifacts
          path: /tmp/artifacts
        env:
          CI: true
