name: terraform test workflow
on: [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
